### ISSUE TITLE
Create `node:10` Docker image with added dependencies

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Corporatesite#15]
The recent update to gulp (#14) requires use of a node 10-based image, however some [added dependencies were needed for `critical`](https://github.com/ebiwd/EBI-Corporatesite/pull/14/files#diff-96edf7a6f008de9e928d04e1ae5e12a5R30):

```
  image: node:10
  tags:      
    - docker        
  before_script:
    - cd ${CI_PROJECT_DIR}       
    - npm install --quiet        
    - npm install -g gulp-cli
    # install dependencies for headless chrome for npm critical module
    - apt-get update && apt-get install -y libnss3 libxss1 libasound2 libpangocairo-1.0-0 libx11-xcb-dev libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libcups2 libxrandr-dev libgconf-2-4 libatk1.0-0 libgtk-3-0
```

As @pwalter-ebi noted, it would be best if we instead have a custom Docker image with the added dependencies pre-installed.

The README.md will also need to be updated to reflect the new image:

```
docker run -it --rm -v $PWD:/workspace -w /workspace simonvanderveldt/node-bower-gulp:6 bash -c 'npm install --quiet && gulp'
```
